version: '3.8'
services:
  tictac-backend:
    build: ./back/tictacback
    ports:
      - "8080:8080" # Expose backend on port 8080
    networks:
      app_network:
        ipv4_address: 10.0.1.2


  tictac-front:
    build: ./front/tictactoe
    ports:
      - "80:80" # Expose frontend on port 4200
    networks:
      app_network:
        ipv4_address: 10.0.1.4

networks:
  app_network:
    ipam:
      config:
        - subnet: 10.0.1.0/24
